version: '3.9'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  redis:
    image: 'redis:latest'
    ports:
      - '6378:6379'
    volumes:
      - 'redis_data:/data'
    command: redis-server --appendonly yes

  inject_programs:
    build:
      context: .
      dockerfile: Dockerfile.mdb
    container_name: inject_programs
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  ywh_programs:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: ywh_programs
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  redis_data: